version: '3.8'

services:
  mysql-product-db:
    image: mysql:8.0
    container_name: mysql-product-db
    environment:
      MYSQL_DATABASE: product_service_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    networks:
      - microservices-net
    volumes:
      - mysql-product-data:/var/lib/mysql

  mysql-order-db:
    image: mysql:8.0
    container_name: mysql-order-db
    environment:
      MYSQL_DATABASE: order_service_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3308:3306"
    networks:
      - microservices-net
    volumes:
      - mysql-order-data:/var/lib/mysql

  discovery-server:
    build: ../discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  product-service:
    build: .
    container_name: product-service
    depends_on:
      - mysql-product-db
      - discovery-server
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-product-db:3306/product_service_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    command: ["java", "-jar", "app.jar"]

  order-service:
    build: ../order-service
    container_name: order-service
    depends_on:
      - mysql-order-db
      - discovery-server
    ports:
      - "8082:8082"
    networks:
      - microservices-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order-db:3306/order_service_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    command: ["java", "-jar", "app.jar"]

  gateway-service:
    build: ../gateway-service
    container_name: gateway-service
    depends_on:
      - discovery-server
      - product-service
      - order-service
    ports:
      - "8080:8080"
    networks:
      - microservices-net
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    command: ["java", "-jar", "app.jar"]

volumes:
  mysql-product-data:
  mysql-order-data:

networks:
  microservices-net: 